[package]
name = "blinky"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkg-config = "0.3.19"
gpio-cdev = "0.4.0"
quicli = "0.4.0"
structopt = "0.3"
tmq = "0.3.0"

